### PR TITLE
Add search hint

### PR DESCRIPTION
**Pull request by hkamran80**

### CODE REVIEW

**Review by Carlgo11 — APPROVED** [review]

**Comment by Carlgo11** [comment]
Thanks for the pull request @hkamran80!
I removed the part about `2fa:totp` as that's actually not being used in v5 😅

**Comment by hkamran80** [comment]
> Thanks for the pull request @hkamran80!

Of course!

> I removed the part about `2fa:totp` as that's actually not being used in v5 😅

How is it not being used?

**Comment by Carlgo11** [comment]
> How is it not being used?

We used jets.js as the search engine before v5. Now Algolia is being used as it improves search times and lowers the initial page load.

A con with Algolia is that it can't handle queries such as `2fa:*`. I'm investigating a way to achieve a similar function, perhaps using Algolia filters, but at the moment no system to filter by 2fa methods exists.

**Comment by hkamran80** [comment]
I see. Hopefully there will be a way!

**Comment by Carlgo11** [comment]
Filters didn't work but something called Faceting Filters worked.
Added in [bc9b5ee](https://github.com/Carlgo11/2fa-dev/commit/bc9b5ee3ba0ace79857746dade281cdcc801b070) :partying_face:

**Comment by hkamran80** [comment]
Cool!

**Pull request merged**
